// Auto-generated schema types will be imported here
// This file is generated by the 'model' command

// Placeholder - will be replaced by generated types
export interface Task {
  // Auto-generated from task.schema.json
}

export interface Metric {
  // Auto-generated from metric.schema.json
}

export interface Threshold {
  // Auto-generated from threshold.schema.json
} 